from os.path import join

# Paths and excel
GIVEN_DATA_PATH = join("data", "datos_entregados.xlsx")
RAIN_DATA_PATH = join("data", "lluvia_generada.xlsx")

LOT_SHEET = "lotes"
MISC_SHEET = "otros"

# Plantas
MAX_DAILY_UNLOAD = 0.3

TIME_RANGE = 7

# Jornaleros
MAX_DIAS_TRABAJO_JORNALERO = 6

# Conductores
MAX_DIAS_TRABAJO_CONDUCTORES = 5

# Tractores
TASA_DEPRECIACION_TRACTOR = 5
COSTO_POR_TONELADA_TRACTOR = 0.1

# Montacargas
TASA_DEPRECIACION_MONTACARGAS = 0
COSTO_POR_TONELADA_MONTACARGAS = 0

# Carro Tolva
TASA_DEPRECIACION_TOLVA = 1.5
COSTO_POR_TONELADA_TOLVA = 0.01

# Cosechadora
TASA_DEPRECIACION_COSECHADORA = 10
COSTO_POR_TONELADA_COSECHADORA = 0.1
VELOCIDAD_COSECHADORA = 4000   # por hora
